site_name: Colemak's Notes
site_url: https://47.115.211.254:8000
site_author: colemak
site_description: colemak's Notes
repo_name: colemak/Notebook
repo_url: https://github.com/wzacolemak/Notebook

nav:
  - Home: index.md
  - Computer Science:
    - CS/index.md
    - 编程语言:
      - Java:
        - Java Security:
          - CS/PL/Java/JavaSec/java_fund.md
          - CS/PL/Java/JavaSec/java_web.md
          - CS/PL/Java/JavaSec/java_web_vul.md
          - CS/PL/Java/JavaSec/java_ram_webshell.md
          - Struts2 漏洞: 
            - CS/PL/Java/JavaSec/Struts2/index.md
          - CS/PL/Java/JavaSec/java_asm.md
          - CS/PL/Java/JavaSec/java_json.md
        - Java Tool: CS/PL/Java/Jtool/Jtools.md
  - CTF: 
    - CTF/index.md
    - WP: 
      - SchoolBus: CTF/WP/SchoolBus/index.md
  - Security:
    - Sec/index.md
    - CVE: Sec/CVE.md
    - Web:
      - SQL注入:
        - Sec/Web/SQL/index.md
      - XSS:
        - Sec/Web/XSS/index.md
      - 反序列化:
        - Sec/Web/Deserial/index.md
        - Common Collections: Sec/Web/Deserial/ACC.md
        - Fastjson: Sec/Web/Deserial/Fastjson.md
        - JDK7u21: Sec/Web/Deserial/JDK7u21.md
      - JNDI 注入: Sec/Web/JNDI/JNDI.md
      - SSTI:
        - Sec/Web/SSTI/index.md
        - Twig: Sec/Web/SSTI/twig.md
        - Smarty: Sec/Web/SSTI/smarty.md

theme:
  font:
    text: LXGW WenKai Screen
    code: JetBrains Mono
  icon: 
    logo: material/notebook-outline #左上角图标
    annotation: material/plus-circle-outline #注释图标
  favicon: assets/favicon.png
  name: material
  custom_dir: overrides
  language: zh
  palette:
    - scheme: default # 日间模式
      primary: indigo # 上方的
      accent: cyan # 链接等可交互元件的高亮色
      toggle:
        icon: material/weather-night # 图标
        name: 切换至夜间模式 # 鼠标悬浮提示
    - scheme: slate # 夜间模式
      primary: black 
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: 切换至日间模式
  features: 
    - content.code.annotate
    - content.code.copy
    - navigation.footer
    - navigation.instant #- header.autohide  #自动隐藏
    #- announce.dismiss #呈现可标记为由用户读取的临时公告，可以包含一个用于取消当前公告的按钮
    - navigation.tracking #地址栏中的 URL 将自动更新为在目录中突出显示的活动锚点
    - navigation.tabs #顶级部分将呈现在上面视口标题下方的菜单层中，但在移动设备上保持原样
    - navigation.tabs.sticky  #启用粘性选项卡后，导航选项卡将锁定在标题下方，并在向下滚动时始终保持可见
    #- navigation.sections #启用部分后，顶级部分在边栏中呈现为1220px以上视口的组，但在移动设备上保持原样
    - navigation.top # 返回顶部的按钮 在上滑时出现
    - search.suggest # 搜索输入一些字母时推荐补全整个单词
    - search.highlight # 搜索出的文章关键词加入高亮
    #- navigation.expand # 打开Tab时左侧目录全部展开
    - navigation.indexes #启用节索引页后，可以将文档直接附加到节
    - search.share #搜索分享按钮

extra:
  homepage: http://47.115.211.254:8000
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/wzacolemak
    - icon: fontawesome/solid/envelope
      link: mailto:<colemak@zju.edu.cn>

plugins:
  - search
  - heti
  - tags:
      tags_file: tags.md
  - encryptcontent:  # now just for one page, need to be improved
      password_file: 'password.yml'
      decryption_failure_message: '密码错误'
      encrypted_something:
        mkdocs-encrypted-toc: [nav, class]
  - git-revision-date-localized:
      type: datetime
      timezone: Asia/Shanghai
      locale: zh
      enable_creation_date: true
      exclude:
        - index.md
  - statistics:
      words_per_minute: 200
      codelines_per_minute: 60
      page_check_metadata: comments
  - glightbox

markdown_extensions:
  - toc:
      permalink: true
      toc_depth: 4
  - def_list
  - attr_list
  - md_in_html
  - sane_lists
  - admonition
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.snippets
  - pymdownx.magiclink
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.inlinehilite
  - pymdownx.smartsymbols
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.tabbed:
      alternate_style: true 
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.arithmatex:
      generic: true
  - meta

extra_javascript:
  - https://cdn.tonycrane.cc/utils/katex.min.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - js/katex.js

extra_css:
  - https://cdn.tonycrane.cc/utils/katex.min.css
  - https://gcore.jsdelivr.net/npm/lxgw-wenkai-screen-webfont@1.7.0/style.css